using System.ComponentModel.DataAnnotations;

namespace DistSysAcwServer.Models
{
    public class Log
    {
        public Log() { }

        public Log(string logString)
        {
            LogString = logString;
            LogDateTime = DateTime.Now;
        }

        [Key]
        public int LogId { get; set; } // Automatically generated by DB 

        [Required]
        public string LogString { get; set; } // Describes what happened 

        [Required]
        public DateTime LogDateTime { get; set; } // Date and time of log 

        public string UserApiKey { get; set; }
    }
}